cmake_minimum_required(VERSION 3.14)
project(macroproject LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(raylib REQUIRED)

add_executable(macroproject
    src/main.cpp
    src/core/grid.cpp
    src/core/solver.cpp
    src/render/renderer.cpp
    src/scenes/block_melt.cpp
    src/scenes/stefan_1d.cpp
    src/export/csv_writer.cpp
    src/scenes/snowflake.cpp
    src/scenes/icicle.cpp
)

target_include_directories(macroproject PRIVATE src)
target_link_libraries(macroproject raylib)